version: "3"
services:
  movie_database:
    image: "postgres"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/mdata/ # persist data even if container shuts down
    networks:
      - recsys
    ports:
      - "2311:5432"

  collector:
    build: ./collector
    command: tail -F anything
    depends_on:
      - movie_database
    networks:
      - recsys
    ports:
      - "2111:2111"

  recommender:
    build: ./recommender
    depends_on:
      - movie_database
    networks:
      - recsys
    ports:
      - "2211:2211"

  result:
    build: ./result
    depends_on:
      - collector
    networks:
      - recsys
    ports:
      - "2411:2411"
    command:
      [
        "./wait-for-it.sh",
        "collector:2111",
        "-t",
        "10",
        "--",
        "node",
        "server.js",
      ]

volumes:
  database-data: 

networks:
  recsys:
    driver: bridge
